---
title: "Analyze FEMA data"
author: "Alan Jackson"
format: html
editor: visual
---

## Combine FEMA and church data to analyze

Produce the following:

1. Map of each hazard by convocation, frequency and annualized occurrence
2. Table for each parish of Hazard, Frequency, Annualized Occurrence


```{r setup}

library(tidyverse)
library(sf)

googlecrs <- "EPSG:4326"
localUTM <- "EPSG:32615"

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"
output_path <- "/home/ajackson/Dropbox/projects/CeationCareTaskforce/"

Parishes <- readRDS(paste0(path, "Parishes_plus_Census_tracts.rds"))

Census <- readRDS(paste0(path, "Census_data_for_Texas_by_tract.rds"))

Convocations <- readRDS(paste0(path,"Convocations.rds")) %>% 
  select(Name) %>% 
  mutate(Label=stringr::str_remove(Name, " Convocation| Region")) %>% 
  sf::st_as_sf()

FEMA <- readRDS(paste0(path, "NRI_Table.rds")) %>% 
  select(Tract=TRACTFIPS, SocVuln=SOVI_SCORE, Resilience=RESL_SCORE, 
         Coastal_Flood_num=CFLD_EVNTS, Coastal_Flood_Freq=CFLD_AFREQ,
         Cold_num=CWAV_EVNTS, Cold_freq=CWAV_AFREQ,
         Drought_num=DRGT_EVNTS, Drought_freq=DRGT_AFREQ,
         Quake_num=ERQK_EVNTS, Quake_freq=ERQK_AFREQ,
         Hail_num=HAIL_EVNTS, Hail_freq=HAIL_AFREQ,
         Heat_num=HWAV_EVNTS, Heat_freq=HWAV_AFREQ,
         Hurricane_num=HRCN_EVNTS, Hurricane_freq=HRCN_AFREQ,
         Ice_num=ISTM_EVNTS, Ice_freq=ISTM_AFREQ,
         Landslide_num=LNDS_EVNTS, Landslide_freq=LNDS_AFREQ,
         Lightning_num=LTNG_EVNTS, Lightning_freq=LTNG_AFREQ,
         River_Flood_num=RFLD_EVNTS, River_Flood_freq=RFLD_AFREQ,
         Wind_num=SWND_EVNTS, Wind_freq=SWND_AFREQ,
         Tornado_num=TRND_EVNTS, Tornado_freq=TRND_AFREQ,
         Wildfire_num=WFIR_EVNTS, Wildfire_freq=WFIR_AFREQ,
         Winter_num=WNTW_EVNTS, Winter_freq=WNTW_AFREQ
         )

```

##        First add list of census tracts to each convocation

```{r add tracts}

Pos_to_GEOID <- function(Position_list, Census_df){
  return(Census_df$GEOID[Position_list])
}

a <- sf::st_intersects(Convocations, Census, sparse=TRUE)

temp <- Census
temp[6897,] <- temp[6896,]
temp$GEOID[6897] <- 0

Convocations$Tract <- list(0)
for (i in 1:nrow(Convocations)) {
  Convocations$Tract[i] <- list(Pos_to_GEOID(a[[i]], temp))
}

Convocations <- sf::st_as_sf(Convocations)


```

##        Maps by convocation of Frequency and Annual Occurrance

```{r convo}

Control <- tribble(~Freq_var, ~Freq_label, ~Freq_units,
                   "Coastal_Flood_Freq", "Coastal Flooding", "Flood/yr",
                   "Cold_freq", "Cold Waves", "Cold Wave Days/yr",
                   "Drought_freq", "Droughts", "Drought Days/yr",
                   "Quake_freq", "Earthquakes", "Quakes/yr",
                   "Hail_freq", "Hail", "Large Hail events/yr",
                   "Heat_freq", "Heat Waves", "Heat Wave Days/yr",
                   "Hurricane_freq", "Hurricane / T.S.", "Hurricanes/yr",
                   "Ice_freq", "Ice Storms", "Ice Storm Days/yr",
                   "Landslide_freq", "Landslides", "Landslides/yr",
                   "Lightning_freq", "Lightning", "Lightning Strikes/yr",
                   "River_Flood_freq", "River Flooding", "Flood Days/yr",
                   "Wind_freq", "Strong Winds", "Strong Wind Events/yr",
                   "Tornado_freq", "Tornados", "Tornados/yr", 
                   "Wildfire_freq", "Wildfire", "Wildfire Probability/yr",
                   "Winter_freq", "Winter Weather", "Winter Weather Days/yr")

Long_Convo <- Convocations %>% 
  sf::st_drop_geometry() %>% 
  unnest_longer(Tract)

Long_Convo <- left_join(Long_Convo, FEMA, by="Tract")

Tract_geoms <- Census %>% 
  select(Tract=GEOID)  

Long_Convo <- Long_Convo %>% 
  left_join(., Tract_geoms, by="Tract") %>% 
  st_as_sf()

Convo_parishes <- Parishes %>% 
  filter(Convocation=="East Harris")

box <- Long_Convo %>%
  filter(Name=="East Harris Convocation") %>% 
  sf::st_bbox() 

Base_basemapR <- basemapR::base_map(box, basemap="mapnik", increase_zoom=2)
  
Long_Convo %>% 
  filter(Name=="East Harris Convocation") %>% 
  ggplot() +
  Base_basemapR +
  geom_sf(aes(fill=Coastal_Flood_Freq) ,alpha=0.5) +
  scale_fill_gradient("Floods/yr", na.value = "transparent", low="white", high="blue") +
  geom_sf(data=Convo_parishes, show.legend=FALSE) +
  ggsflabel::geom_sf_label_repel(data=Convo_parishes, aes(label=Label), 
                                 size=2, max.overlaps=20, force=100) +
  labs(title="FEMA Coastal Flooding Frequency, East Harris Convocation ",
       subtitle="Number of expected floods each year, per census tract") +
  annotate("text", label="
         Data sourced from FEMA, National Risk Index, March 2023 
         Map a product of Alan Jackson", 
         x=-Inf, 
         y=-Inf,
         hjust="inward", vjust="inward", size = 3)

  # ggsave(paste0(output_path, "FEMA_",i,"_slosh_model.jpg"))
```





