---
title: "Create better convocations"
author: "Alan Jackson"
format: html
editor: visual
---

## Create a better convocation map from a county list

```{r setup}

library(tidyverse)

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"

data_path <- "/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/Texas_Counties/"
Counties <- readRDS(paste0(data_path, "County_Outlines.rds"))

Old_Convo <- readRDS(paste0(path,"Convocations.rds")) %>% 
  select(Name) %>%
  mutate(Label=stringr::str_remove(Name, " Convocation| Region")) %>%
  sf::st_as_sf()

```

### Read in counties and create dataframe

```{r}

New_convo <- NULL

add_convo <- function(New_convo, foo) {
  as_tibble(foo[2:length(foo)]) %>% 
  rename(County=value) %>% 
  mutate(Convocation=foo[1]) %>% 
  select(Convocation, County) %>% 
  bind_rows(New_convo, .)
}

New_convo <- add_convo(New_convo, c("North", "Wichita", "Clay", "Montague", "Cooke", "Archer", "Young", "Jack", "Wise", "Stephens", "Palo Pinto", "Parker", "Tarrant", "Eastland", "Erath", "Hood", "Johnson", "Somerville", "Comanche", "Bosque", "Hill", "Hamilton", "Mills", "Brown"))
New_convo <- add_convo(New_convo, c("Austin", "Lampasas", "Burnet", "Williamson", "Travis", "Bastrop", "Lee"))
New_convo <- add_convo(New_convo, c("Northwest", "Coryell", "McLennan", "Limestone", "Freestone", "Bell", "Falls", "Milam"))
New_convo <- add_convo(New_convo, c("Northeast", "Marion", "Smith", "Gregg", "Harrison", "Anderson", "Cherokee", "Rusk", "Panola", "Houston", "Trinity", "Angelina", "Nacogdoches", "Shelby", "San Augustine", "Sabine"))
New_convo <- add_convo(New_convo, c("Central", "Robertson", "Leon", "Burleson", "Brazos", "Madison", "Grimes", "Fayette", "Washington", "Austin", "Waller"))
New_convo <- add_convo(New_convo, c("San Jacinto", "Walker", "San Jacinto", "Polk", "Montgomery", "Liberty"))
New_convo <- add_convo(New_convo, c("Southeast", "Tyler", "Jasper", "Newton", "Hardin", "Orange", "Jefferson", "Chambers"))
New_convo <- add_convo(New_convo, c("Galveston", "Galveston", "Brazoria"))
New_convo <- add_convo(New_convo, c("Southwest", "Colorado", "Wharton", "Matagorda", "Fort Bend"))
New_convo <- add_convo(New_convo, c("Harris", "Harris"))

```

### Combine with county coordinates

```{r}

Better_convo <- inner_join(New_convo, Counties, by=c("County"="CNTY_NM")) %>% 
  sf::st_as_sf() %>% 
  select(Convocation, County) 

#   Export to shapefile so I can manually split harris county

  sf::st_write(Better_convo, paste0(path, "Better_Convo"),
               driver = "ESRI Shapefile",
               delete_layer = TRUE)  # create to a shapefile


```

### After hand-editing in Qgis to split Harris county, read back in

```{r}

Better_convocation <- sf::st_read(paste0(path, "Better_Convo/Better_Convos.shp"))

tmap::tmap_options(basemaps="OpenStreetMap")

tmap::tmap_mode("view") # set mode to interactive plots

# map <- 
  tmap::tm_shape(Better_convocation) + 
  tmap::tm_fill(col = "Convctn", title = "Convocation", alpha=0.5, style="pretty")+
  tmap::tm_borders(lwd=0.2) +
  tmap::tm_shape(Parishes) + 
  tmap::tm_dots()
```

### Add Somervell county and combine Harris and San Jacinto Convocations

```{r}

#   Add Somervell county
Conv1 <- Counties %>% 
  filter(CNTY_NM=="Somervell") %>% 
  select(CNTY_NM) %>%
  mutate(Convctn="North") %>% 
  rename(County=CNTY_NM) %>% 
  # sf::st_join(Better_convocation, ., by=c("County"="CNTY_NM")) %>% 
  rbind(Better_convocation, .) %>% 
  sf::st_as_sf() %>% 
  select(Convocation=Convctn, County) 

#   Combine Harris and San Jacinto Convos

Conv2 <- Conv1 %>% 
  mutate(Convocation=ifelse(Convocation=="Harris", "San Jacinto", Convocation))

tmap::tmap_options(basemaps="OpenStreetMap")

tmap::tmap_mode("view") # set mode to interactive plots

# map <- 
  tmap::tm_shape(Conv2) + 
  tmap::tm_fill(col = "Convocation", title = "Convocation", alpha=0.5, style="pretty")+
  tmap::tm_borders(lwd=0.2) +
  tmap::tm_shape(Parishes) + 
  tmap::tm_dots()
  
#   Overwrite old file  
  
Conv2 %>% 
  rename(Label=Convocation) %>% 
  write_rds(paste0(path,"Convocations.rds"))

```
