---
title: "Create Shapefiles"
author: "Alan Jackson"
format: html
editor: source
---

## Create shapefiles

Read in diocesan and convocation boundaries and export as shapefiles

```{r setup}

library(tidyverse)

Arc_CRS <- "EPSG:4735"

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"
Curated_path <- "/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/Texas_Counties/"

Convocations <- readRDS(paste0(path,"Convocations.rds")) %>% 
  select(Name) %>% 
  mutate(Label=stringr::str_remove(Name, " Convocation| Region")) %>% 
  sf::st_as_sf()

Counties <- readRDS(paste0(Curated_path, "County_Outlines.rds")) %>% 
  sf::st_transform(googlecrs)

Parishes <- readRDS(paste0(path, "Parishes.rds")) %>% 
  select(Label, City) %>% 
  mutate(Name=stringr::str_remove_all(Label, "[^a-zA-Z ]")) %>% 
  mutate(Name=stringr::str_remove(Name, "The Episcopal Church of t?h?e? ?")) %>% 
  mutate(Name=paste(Name, City)) %>% 
  mutate(Name=stringr::str_remove(Name, " \\(temp\\)")) 

```

### create a shapefile of parish locations

```{r}

  sf::st_write(Parishes %>% sf::st_transform(Arc_CRS), paste0(path, "Parishes"),
               driver = "ESRI Shapefile",
               delete_layer = TRUE)  # create to a shapefile

```

### Make a map of counties and diocesan convocations

```{r}

tmap::tmap_options(basemaps="OpenStreetMap")

tmap::tmap_mode("view") # set mode to interactive plots

tmap::tm_shape(Convocations) + 
    #tmap::tm_sf(col="ConvoColor", alpha=0.3) +
  tmap::tm_fill(title = "Convocations", alpha=0.3, style="pretty")+
  tmap::tm_borders(lwd=3, col="red") +
tmap::tm_shape(Counties) + 
  # tmap::tm_fill(title = "Convocations", alpha=0.3, style="pretty")+
  tmap::tm_borders() 




```

```{r}

Convocations %>% 
  mutate(area=units::drop_units(sf::st_area(geometry))/4046.86) %>% 
  group_by(Label) %>% 
  summarize(area = sum(area)/10000000)

#   Split North convocation in four

Convocations[1:6,]$Label <- "NorthA"
Convocations[7:11,]$Label <- "NorthB"
Convocations[12:17,]$Label <- "NorthC"
Convocations[18:22,]$Label <- "NorthD"
Convocations[82,]$Label <- "NorthD"

#   Combine counties to get just the big polygons

Convo_only <- Convocations %>% 
  group_by(Label) %>% 
  summarize(geometry = sf::st_union(geometry)) %>% 
  sf::st_make_valid()

tmap::tmap_options(basemaps="OpenStreetMap")

tmap::tmap_mode("view") # set mode to interactive plots

tmap::tm_shape(Convo_only) + 
  tmap::tm_fill(title = "Convocations", alpha=0.3, style="pretty")+
  tmap::tm_borders(lwd=3, col="red") +
tmap::tm_shape(Counties) + 
  tmap::tm_borders() 


for (i in 1:14) {
  Convo <- Convo_only[i,] %>% sf::st_make_valid() %>% 
    mutate(Name=stringr::str_replace_all(Label, " ", ""))
  Name <- stringr::str_replace_all(Convo$Label, " ", "_")
  sf::st_write(Convo, paste0(path, Name),
               driver = "ESRI Shapefile",
               delete_layer = TRUE)  # create to a shapefile
}

```

## Can I read Fire output

```{r}

# sf::st_layers(paste0(path, "Fire/TxPortal_Export_TestNorth_20231208_193925.gdb"))
# fire <- sf::st_read(paste0(path, "Fire/TxPortal_Export_TestNorth_20231208_193925.gdb"),
#                     layer = "Threat_UP_i")

fire <- terra::rast(paste0(path, "Fire/Threat_UP.geotiff"))

tmap::tmap_options(basemaps="OpenStreetMap")

tmap::tmap_mode("view") # set mode to interactive plots

tmap::tm_shape(fire) + 
    #tmap::tm_sf(col="ConvoColor", alpha=0.3) +
  # tmap::tm_fill(title = "Threat", alpha=0.3, style="pretty") +
  tmap::tm_raster(alpha=0.3)
  # tmap::tm_borders(lwd=3, col="red") 
```
