---
title: "Hail analysis"
author: "Alan Jackson"
format: html
editor: source
---

## Analyze Hail data

```{r setup}

library(tidyverse)
library(gt)

googlecrs <- "EPSG:4326"
localUTM <- "EPSG:32615"

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"
Curated_path <- "/home/ajackson/Dropbox/Rprojects/Curated_Data_Files/Texas_Counties/"
out_path <- "/home/ajackson/Dropbox/projects/CeationCareTaskforce/Maps_and_tables/Hail/"

Parishes <- readRDS(paste0(path, "Parishes.rds"))

Counties <- readRDS(paste0(Curated_path, "County_Outlines.rds")) %>% 
  sf::st_transform(googlecrs)

Hail <- readRDS(paste0(path, "NRI_Table_Counties.rds")) %>% 
  select(COUNTY, COUNTYFIPS, AREA, 
         HAIL_EXP_AREA, HAIL_EVNTS, HAIL_AFREQ, HAIL_EXPT) %>% 
  mutate(EventsPerSqMi=100*HAIL_AFREQ/AREA) %>% 
  mutate(PctAreaHit=100*HAIL_EVNTS*6/AREA) %>% 
  mutate(Years50=pmin(log(1-0.5)/log(1-HAIL_AFREQ*6/AREA), 50)) %>% 
  mutate(Years90=pmin(log(1-0.9)/log(1-HAIL_AFREQ*6/AREA), 50)) %>% 
  mutate(RetPer=pmin(1/(HAIL_AFREQ*6/AREA), 70)) %>% 
  mutate(Prob25=1-(1-HAIL_AFREQ*6/AREA)**25) %>% 
  mutate(COUNTY=stringr::str_replace(COUNTY, "DeWitt", "De Witt"))

```

##        Map Hail events per year per sq mi per county

```{r}

Hail_exp <- Hail %>% 
  left_join(., Counties, by=c("COUNTY" = "CNTY_NM")) %>%  
  sf::st_as_sf()


tmap::tmap_options(basemaps="OpenStreetMap")

tmap::tmap_mode("view") # set mode to interactive plots

tmap::tm_shape(Hail_exp) + 
  tmap::tm_fill(col = "Prob25", title = "Prob of Hail in 25 years", alpha=0.5, style="pretty")+
tmap::tm_shape(Hail_exp) + 
  tmap::tm_fill(col="RetPer", title="Return Period in years", alpha=0.5, style="pretty") +
  tmap::tm_borders(lwd=0.2) +
  tmap::tm_shape(Parishes) + 
  tmap::tm_dots()


```

##    Map expected return period and 25 year probability

```{r}

bbox <- sf::st_bbox(Parishes)

Base_basemapR <- basemapR::base_map(bbox, basemap="mapnik", increase_zoom=2)

#   All points

Hail_exp %>% 
  ggplot() +
  Base_basemapR +
  geom_sf(aes(fill=RetPer) ,alpha=0.5) +
  scale_fill_gradient(name="Hail Return Period in Years", 
                      na.value = "transparent", 
                      low="yellow",
                      high="brown",
                      breaks=c(5,15,25,35,45),
                      labels=c('10', '20', '30', '40', '>50'),
                      limits=c(3, 50)) +
  geom_sf(data=Parishes, show.legend=FALSE) +
  labs(title=paste("Hail Return Period for Churches in the Diocese"),
       x="Longitude",
       y="Latitude") +
  annotate("text", label=
           "Data sourced from FEMA 
           Map a product of Alan Jackson", 
           x=-Inf, 
           y=-Inf,
           hjust="inward", vjust="inward", size = 2) +
  coord_sf(xlim=c(bbox$xmin, bbox$xmax),c(bbox$ymin, bbox$ymax))

  ggsave(paste0(out_path, "Hail_Return_Period_Map.jpg"))
  
#   25 year probability
  
Hail_exp %>% 
  ggplot() +
  Base_basemapR +
  geom_sf(aes(fill=Prob25) ,alpha=0.5) +
  scale_fill_gradient(name="Probability of Hail in 25 Years", 
                      na.value = "transparent", 
                      low="yellow",
                      high="brown",
                      # breaks=c(5,15,25,35,45),
                      # labels=c('10', '20', '30', '40', '>50'),
                      # limits=c(3, 50)
                      ) +
  geom_sf(data=Parishes, show.legend=FALSE) +
  labs(title=paste("Probability of Hail over 25 Years for Churches in the Diocese"),
       x="Longitude",
       y="Latitude") +
  annotate("text", label=
           "Data sourced from FEMA 
           Map a product of Alan Jackson", 
           x=-Inf, 
           y=-Inf,
           hjust="inward", vjust="inward", size = 2) +
  coord_sf(xlim=c(bbox$xmin, bbox$xmax),c(bbox$ymin, bbox$ymax))

  ggsave(paste0(out_path, "Hail_Probability_Map.jpg"))
  

```

##        Tables

```{r}

table <- Hail_exp %>% 
  inner_join(., Churches, by=c("COUNTY"="County")) %>% 
  select(Label, City, RetPer, Prob25) %>% 
  mutate(Prob25=Prob25/2) %>% 
  arrange(RetPer) %>% 
  # filter(RetPer<30) %>% 
  sf::st_drop_geometry() %>% 
  gt::gt() %>% 
    gt::tab_header(
      title="Hail hazard for Churches",
      # subtitle="Return periods of less than 30 years"
    ) %>% 
    gt::fmt_number(
      
    ) %>% 
    gt::cols_label(
      Label="Church",
      City="City",
      RetPer=html("Return Period<br>(years)"),
      Prob25=html("Damage Probability<br>over 25 Years")
  )

gt::gtsave(table, paste0(out_path, "Hail_table.docx"))

```





