---
title: "Read_Convocations"
author: "Alan Jackson"
format: html
editor: source
---

## Read convocation coordinate file

```{r setup}

library(tidyverse)

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"

```

## Read the data

```{r read data in (and save it)}

foo <- sf::st_read(paste0(path, "The Episcopal Diocese of Texas.kml"))

Convocations <- foo %>% 
  filter(stringr::str_detect(Name, "Convocation|Region")) %>% 
  mutate(ConvoColor=row_number())

#   Add convocation to parish

Parishes <- foo %>% 
  mutate(Convocation=NA)

for (i in 1:nrow(foo)){
  if (stringr::str_detect(foo[i,]$Name, "Convocation|Region")){  
    Convo <- foo[i,]$Name
  }
  print(Convo)
  Parishes[i,]$Convocation <- Convo 
}

Parishes <- Parishes %>% 
  filter(!stringr::str_detect(Name, "Convocation|Region")) %>% 
  mutate(description=stringr::str_replace(description, "http://trinitywoodlands.org/", 
                                          "3901 South Panther Creek Drive<br>The Woodlands, TX 77381<br>281-367-8113<br>trinitywoodlands.org (https://www.trinitywoodlands.org/)"))

#   Create shorter Label names for churches

Parishes <- Parishes %>% 
  mutate(Label=stringr::str_remove(Name, " Episcopal Church$")) %>% 
  mutate(Label=stringr::str_replace(Label, "^Christ$", "Christ Church")) %>% 
  mutate(Label=stringr::str_remove(Label, "^Episcopal Church of the ")) %>% 
  mutate(Label=stringr::str_remove(Label, " Episcopal Church and School")) %>% 
  mutate(Label=stringr::str_remove(Label, " Episcopal Church & School")) %>% 
  mutate(Label=stringr::str_remove(Label, "The Church of ")) %>% 
  mutate(Label=stringr::str_remove(Label, " - Leigh")) %>% 
  mutate(Label=stringr::str_replace(Label, "The Episcopal Church of Hamilton County", "St. Mary's")) %>% 
  mutate(description=stringr::str_replace(description, "St. Catherine's Episcopal Church",
                                          "1101 S Rice St, Hamilton, TX 76531")) %>% 
  select(Name, Label, Description=description, Convocation) %>% 
  st_as_sf()
  
Parishes[54,]$Description <- "7615 FM 762 Rd<br>Richmond, TX 77469"
Parishes[50,]$Description <- "5653 W Riverpark Dr<br>Sugar Land, TX 77479"

Parishes <- Parishes %>% 
  mutate(Convocation = stringr::str_remove(Convocation, " Convocation")) %>% 
  mutate(City=stringr::str_split_i(Description, "<br>|,", 2)) %>% 
  select(Name, Label, City, Description, Convocation) %>% 
  st_as_sf()

Parishes[149,]$City <- "Marlin"
Parishes[149,]$Description <- "514 Carter St<br>Marlin, TX 76661"
Parishes[149,]$Convocation <- "Northwest"
Parishes[153,]$Label <- "St. Matthew's"

Special_cases <- c(1,2,4,22,39,73,82,109,113,117,144,150:162)
Special_values <- c(rep("Houston",5), "Beaumont", "Bryan", "Round Rock", "Manor (temp)",
                    "Round Rock", "Leigh", "Arlington (temp)", "Decatur (temp)", 
                    "Fort Worth (temp)", "Fort Worth (temp)", "Fort Worth (temp)",
                    "Fort Worth (temp)", "Granbury (temp)", "Hamilton", "Hillsboro (temp)",
                    "Hurst (temp)", "Keller", "Stephenville", "Wichita Falls (temp)")

Parishes[Special_cases,]$City <- Special_values
  
saveRDS(Convocations, paste0(path, "Convocations.rds"))
saveRDS(Parishes, paste0(path, "Parishes.rds"))

```

## Plot the data

```{r plot}

#   Plot

tmap::tmap_options(basemaps="OpenStreetMap")

tmap::tmap_mode("view") # set mode to interactive plots


tmap::tm_shape(Convocations) + 
    #tmap::tm_sf(col="ConvoColor", alpha=0.3) +
  tmap::tm_fill(col = "ConvoColor", title = "Convocation", alpha=0.3, style="cat")+
  tmap::tm_borders() +
  tmap::tm_shape(Parishes) + 
    tmap::tm_dots()


```
