---
title: "Read FEMA data"
author: "Alan Jackson"
format: html
editor: source
---

## Read FEMA data

FEMA data by census tract in a csv file

https://hazards.fema.gov/nri/ https://hazards.fema.gov/nri/data-resources#csvDownload

```{r setup}

library(tidyverse)

googlecrs <- "EPSG:4326"
localUTM <- "EPSG:32615"

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"

Parishes <- readRDS(paste0(path, "Parishes.rds"))

```

## Read tract level data

```{r read csv file}

df <- read_csv(paste0(path, "NRI_Table_CensusTracts_Texas.csv"),
               col_types="ccccccccccciii?") %>% 
  select(NRI_ID, COUNTY, COUNTYFIPS, STCOFIPS, TRACT, TRACTFIPS, POPULATION, AREA, 
         SOVI_SCORE, RESL_SCORE, 
         CFLD_EVNTS, CFLD_AFREQ, CFLD_EXPT, CFLD_EXP_AREA,
         CWAV_EVNTS, CWAV_AFREQ, CWAV_EXPT, CWAV_EXP_AREA,
         DRGT_EVNTS, DRGT_AFREQ, DRGT_EXPT, DRGT_EXP_AREA,
         ERQK_EVNTS, ERQK_AFREQ, ERQK_EXPT, ERQK_EXP_AREA,
         HAIL_EVNTS, HAIL_AFREQ, HAIL_EXPT, HAIL_EXP_AREA,
         HWAV_EVNTS, HWAV_AFREQ, HWAV_EXPT, HWAV_EXP_AREA,
         HRCN_EVNTS, HRCN_AFREQ, HRCN_EXPT, HRCN_EXP_AREA,
         ISTM_EVNTS, ISTM_AFREQ, ISTM_EXPT, ISTM_EXP_AREA,
         LNDS_EVNTS, LNDS_AFREQ, LNDS_EXPT, LNDS_EXP_AREA,
         LTNG_EVNTS, LTNG_AFREQ, LTNG_EXPT, LTNG_EXP_AREA,
         RFLD_EVNTS, RFLD_AFREQ, RFLD_EXPT, RFLD_EXP_AREA,
         SWND_EVNTS, SWND_AFREQ, SWND_EXPT, SWND_EXP_AREA,
         TRND_EVNTS, TRND_AFREQ, TRND_EXPT, TRND_EXP_AREA,
         WFIR_EVNTS, WFIR_AFREQ, WFIR_EXPT, WFIR_EXP_AREA,
         WNTW_EVNTS, WNTW_AFREQ, WNTW_EXPT, WNTW_EXP_AREA
         )

saveRDS(df, paste0(path, "NRI_Table.rds"))

```

## Read county level data

```{r read csv file}

df <- read_csv(paste0(path, "NRI_Table_Counties_Texas.csv")) %>% 
               # col_types="ccccccccccciii?") %>% 
  select(NRI_ID, COUNTY, COUNTYFIPS, STCOFIPS, POPULATION, AREA, 
         SOVI_SCORE, RESL_SCORE, 
         CFLD_EVNTS, CFLD_AFREQ, CFLD_EXPT, CFLD_EXP_AREA,
         CWAV_EVNTS, CWAV_AFREQ, CWAV_EXPT, CWAV_EXP_AREA,
         DRGT_EVNTS, DRGT_AFREQ, DRGT_EXPT, DRGT_EXP_AREA,
         ERQK_EVNTS, ERQK_AFREQ, ERQK_EXPT, ERQK_EXP_AREA,
         HAIL_EVNTS, HAIL_AFREQ, HAIL_EXPT, HAIL_EXP_AREA,
         HWAV_EVNTS, HWAV_AFREQ, HWAV_EXPT, HWAV_EXP_AREA,
         HRCN_EVNTS, HRCN_AFREQ, HRCN_EXPT, HRCN_EXP_AREA,
         ISTM_EVNTS, ISTM_AFREQ, ISTM_EXPT, ISTM_EXP_AREA,
         LNDS_EVNTS, LNDS_AFREQ, LNDS_EXPT, LNDS_EXP_AREA,
         LTNG_EVNTS, LTNG_AFREQ, LTNG_EXPT, LTNG_EXP_AREA,
         RFLD_EVNTS, RFLD_AFREQ, RFLD_EXPT, RFLD_EXP_AREA,
         SWND_EVNTS, SWND_AFREQ, SWND_EXPT, SWND_EXP_AREA,
         TRND_EVNTS, TRND_AFREQ, TRND_EXPT, TRND_EXP_AREA,
         WFIR_EVNTS, WFIR_AFREQ, WFIR_EXPT, WFIR_EXP_AREA,
         WNTW_EVNTS, WNTW_AFREQ, WNTW_EXPT, WNTW_EXP_AREA
         )

saveRDS(df, paste0(path, "NRI_Table_Counties.rds"))

```
