---
title: "Repair Parishes"
author: "Alan Jackson"
format: html
editor: source
---

##    Update addresses and locations and names

```{r}

library(tidyverse)

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"

google_crs <- "EPSG:4326" # lat long

Parishes <- readRDS(paste0(path, "Parishes.rds"))  

Parishes[Parishes$ID==151,]$Description <- "905 South Church Street<br>Decatur, TX 76234" 
Parishes[Parishes$ID==151,]$City <- "Decatur" 
Parishes[Parishes$ID==155,]$Description <- "3401 Bellaire Drive South<br>Fort Worth, TX 76109" 
Parishes[Parishes$ID==155,]$City <- "Fort Worth" 
Parishes[Parishes$ID==156,]$Description <- "4530 Acton Hwy<br>Granbury, TX 76049" 
Parishes[Parishes$ID==156,]$City <- "Granbury" 
Parishes[Parishes$ID==157,]$Description <- "1101 South Rice Street<br>Hamilton, TX 76531" 
Parishes[Parishes$ID==157,]$City <- "Hamilton" 
Parishes[Parishes$ID==160,]$Description <- "223. S. Pearson Lane<br>Keller, TX 76248" 
Parishes[Parishes$ID==160,]$City <- "Keller" 
Parishes[Parishes$ID==161,]$Description <- "595 N. McIlhaney St.<br>Stephenville, TX 76401" 
Parishes[Parishes$ID==161,]$City <- "Stephenville" 
Parishes[Parishes$ID==158,]$Description <- "301 S. Waco Street<br>Hillsboro, TX 76645" 
Parishes[Parishes$ID==158,]$City <- "Hillsboro" 

Parishes <- Parishes %>% 
  mutate(Zip=stringr::str_extract(Description, "(TX|Texas) \\d{5}")) %>%
  mutate(Zip=stringr::str_remove(Zip, "TX ")) %>% 
  mutate(Zip=stringr::str_remove(Zip, "Texas "))

Parishes[Parishes$ID==98,]$Zip <- "78626"

saveRDS(Parishes, paste0(path, "Parishes.rds"))

```

##        Repair St Francis Asis

```{r}

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"

Parishes <- read_rds(paste0(path, "Parishes.rds")) 

sfc = sf::st_sfc(sf::st_point(c(-97.80217346676257, 30.199313909582955)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

sf::st_geometry(Parishes[Parishes$ID==100,]) <- sfc

write_rds(Parishes, paste0(path, "Parishes.rds")) 

```


##        Repair St Alban's Austin

```{r}

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"

Parishes <- read_rds(paste0(path, "Parishes.rds")) 

sfc = sf::st_sfc(sf::st_point(c(-97.7982735358955, 30.129794015276314)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

sf::st_geometry(Parishes[Parishes$ID==100,]) <- sfc

write_rds(Parishes, paste0(path, "Parishes.rds")) 

```

##        Repair Episcopal church of the epiphany houston

```{r}

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"

Parishes <- read_rds(paste0(path, "Parishes.rds")) 

sfc = sf::st_sfc(sf::st_point(c(-95.52906697527352, 29.67598071488963)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

sf::st_geometry(Parishes[Parishes$ID==19,]) <- sfc

write_rds(Parishes, paste0(path, "Parishes.rds")) 

```


##        Major repositioning to get lat long into main church building

```{r}

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"

Parishes <- read_rds(paste0(path, "Parishes.rds")) 

Updates <- tribble(~ID, ~Lat, ~Lon,
                    94, 30.11141678623458, -97.32030491525285,
                    95, 30.51117445839927, -97.88148531076389,
                   101, 30.12981232575694, -97.79826755279615,
                   104, 30.300180272450817, -97.71546541954083,
                   105, 30.282415467504066, -97.67347033539613,
                   106, 29.908103063889786, -96.87357095589623,
                   108, 30.385511214064007, -97.6954686623192,
                   115, 30.318714450045533, -97.82351436602461,
                   118, 30.57489629040363, -98.26776200868086,
                    80, 30.97970015710672, -96.66973906242352,
                    85, 30.08716625118095, -95.99296846954034,
                    87, 29.778121941374447, -96.15704895327733,
                    90, 30.146861865678144, -96.39538116821176,
                    91, 30.878586461132283, -96.59579388191001,
                     3, 29.673558422774985, -95.44390337665259,
                     4, 29.739528945859455, -95.3772400695104,
                     6, 29.810544956635017, -95.36585229531049,
                     8, 29.656084752904796, -95.01887878307791,
                    11, 29.685770994336405, -95.28220173036193,
                    12, 29.70067671963361, -95.19846132977823,
                    13, 29.784913203226036, -95.19395091015583,
                    14, 29.77921728261291, -94.96321292792642,
                    59, 29.361817880381366, -95.05542336664213,
                    60, 29.51589628507925, -95.19159909424025,
                    61, 29.421445383306725, -95.24514100170221,
                    62, 29.294495513331064, -94.80663637913963,
                    65, 29.553583596937177, -95.25625149374717,
                    66, 29.522017993863958, -95.07439929399841,
                    68, 29.364140898021002, -94.97912961522684,
                    69, 29.546028143737395, -95.08820042099185,
                   156, 32.44466909377118, -97.71462907433322,
                   130, 31.32196603416178, -95.4439160528685,
                   131, 32.75559968697449, -94.35054983728725,
                   132, 31.615754070597955, -94.6488666008193,
                   133, 31.5283102671064, -94.10582989403643,
                   135, 31.323244645017216, -94.75334560864209,
                   136, 32.313248368355325, -95.28482060185206,
                   138, 31.783300313306192, -94.18492349842921,
                   139, 32.36665371795978, -95.30595790506071,
                   140, 32.50258727895171, -95.41853380722054,
                   141, 32.143911212554876, -94.79664939254667,
                   142, 32.53142686022557, -94.7942964815397,
                   147, 32.49896410911372, -94.72853331569443,
                   148, 32.5452827339046, -94.37101272544412,
                   144, 32.60401462566081, -94.13947263346613,
                   120, 31.68157689466559, -96.48009490162862,
                   121, 31.10026171328197, -97.34021726052185,
                   124, 31.086802967821722, -97.73457911663368,
                   125, 31.060022963623656, -97.3963797857281,
                    35, 30.10486103306321, -95.60645804268135,
                    36, 30.067587992889006, -95.45154086990813,
                    39, 29.99100248664615, -95.5020725265391,
                    41, 30.343146465070344, -95.5216497342029,
                    42, 29.99726612472906, -95.61447574036498,
                    71, 29.976501256603715, -93.96528294684148,
                    72, 30.35783314767158, -94.19118087559356,
                    74, 30.098996023782775, -93.74394271225074,
                    75, 30.773322557667417, -94.43626591856052,
                    76, 30.10562291024371, -94.14519681963316,
                    77, 30.060018373825155, -94.79486661771091,
                    45, 29.61945043310888, -95.58193310369091,
                    50, 29.576008419668856, -95.68222640139854,
                    51, 29.51823045194183, -95.53082699905974,
                    52, 28.70168823995787, -96.2131845943077,
                    54, 29.52322811147232, -95.69580619012662,
                    56, 28.951651574913928, -95.36405886781738,
                    57, 29.321336167202087, -96.09415762349767,
                    58, 29.042674534797207, -95.44039604057636,
                    16, 29.7388980473836, -95.55280313805088,
                    17, 29.69924150752031, -95.6568203284868,
                    19, 29.675785785905127, -95.52872019003051,
                    22, 29.830023284677267, -95.44031840472985,
                    23, 29.70802768475225, -95.4801155226108,
                    24, 29.674804560770873, -95.60037171803545,
                    26, 29.8033884199501, -95.5237652926317,
                    32, 29.68498822523036, -95.46435034780721
                   )

Addresses <- tribble(~ID, ~Description,
                     80, "501 Gregg St, Calvert, TX 77837<br>(979) 364-3784",
                     35, "715 Carrell St, Tomball, TX 77375<br>(281) 351-1609<br>goodshepherdtomball.org (http://goodshepherdtomball.org)",
                     16, "2525 Seagler Road, Houston, TX 77042-3194<br>(713) 781-1330<br>ascensionepiscopalchurch.org (http://ascensionepiscopalchurch.org)"
                     )

#   Delete ID 157, St. Mary's, Hamilton

sfc = sf::st_sfc(sf::st_point(c(-95.52906697527352, 29.67598071488963)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

sf::st_geometry(Parishes[Parishes$ID==19,]) <- sfc

write_rds(Parishes, paste0(path, "Parishes.rds")) 
```

