---
title: "Storm Surge Analysis"
author: "Alan Jackson"
format: html
editor: visual
---

## Storm Surge Analysis

1.  Build a table of which churches are affected under each storm category
2.  Define AOI's for maps to illustrate the different areas
3.  Build the maps
4.  Extend the maps and tables with Sealevel rise?

## Setup

Read in files and get everything onto the same CRS

We will do all our work in EPSG:4269 since the GeoTIFF data comes in that CRS.

```{r setup}
library(tidyverse)
library(terra)
library(tidyterra)
library(gt)

googlecrs <- "EPSG:4326"
localUTM <- "EPSG:32615"
inputcrs <- "EPSG:4269" # from metadata file

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"
output_path <- "/home/ajackson/Dropbox/projects/CeationCareTaskforce/"

Parishes <- readRDS(paste0(path, "Parishes.rds"))

#   Transform Parishes to the GeoTIFF input grid and add an ID needed later for joins
Parishes <- sf::st_transform(Parishes, crs=inputcrs) %>% 
  mutate(ID=row_number())

#   Define some 100 m polygons around each church
Parish_polys <- Parishes %>% 
  sf::st_buffer(100) %>% sf::st_as_sf() # Units are meters

#   Define an AOI
bbox <- sf::st_bbox(Parishes)

bbox["xmin"] <- -96.38
bbox["xmax"] <- -93.66
bbox["ymin"] <- 28.39
bbox["ymax"] <- 30.47

#   Expand box by 20% to give a little extra room
expand_box <- function(bbox, pct=0.2){
  Dx <- (bbox[["xmax"]]-bbox[["xmin"]])*pct
  Dy <- (bbox[["ymax"]]-bbox[["ymin"]])*pct
  bbox["xmin"] <- bbox["xmin"] - Dx
  bbox["xmax"] <- bbox["xmax"] + Dx
  bbox["ymin"] <- bbox["ymin"] - Dy
  bbox["ymax"] <- bbox["ymax"] + Dy
  return(bbox)
}

Basemap_attribution <- 'attribution: &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
```

```{r Read in grids}

for (i in 1:5){
  
  x <- terra::rast(paste0(path, "US_SLOSH_MOM_Inundation_v3/us_Category",i,"_MOM_Inundation_HIGH.tif")) 
  
  #   Clip to AOI
  
  Slosh <- terra::crop(x, bbox)
  rm(x)
  Slosh <- ifel(Slosh==99, NA, Slosh)
  Slosh <- as.numeric(Slosh)
  
  #   Extract values at church locations
  
  Church_values <- Slosh %>% 
    terra::extract(vect(Parish_polys), method="bilinear", ID=TRUE) %>% 
      group_by(ID) %>% 
      summarize(value=mean(data_range, na.rm=TRUE)) %>% 
    filter(!is.nan(value)) %>% 
    filter(value<99) %>% 
    inner_join(., Parishes, by="ID") %>% 
    sf::st_as_sf()
  
  saveRDS(Church_values, paste0(path, "Churches_Stormsurge_Cat", i, ".rds"))
  
  box <- Church_values %>%
    sf::st_bbox() %>% expand_box(., 0.2)
  
  Base_basemapR <- basemapR::base_map(box, basemap="mapnik", increase_zoom=2)
  
  Church_values %>% 
    rename(Feet=value) %>% 
    ggplot() +
    Base_basemapR +
    geom_spatraster(data=Slosh, alpha=0.3) +
    scale_fill_gradient("Surge in Feet", na.value = "transparent", low="white", high="blue") +
    geom_sf(aes(
      size=Feet), show.legend=TRUE) +
    ggsflabel::geom_sf_label_repel(aes(label=paste(Label, signif(Feet,2), "ft")),
                                    size=2, max.overlaps=20, force=100) +
    labs(title=paste("SLOSH model from NOAA, Cat", i, "Hurricane Storm Surge in feet"),
         x="Longitude",
         y="Latitude") +
    coord_sf(xlim=c(box$xmin, box$xmax),c(box$ymin, box$ymax))
  
  ggsave(paste0(output_path, "Cat_",i,"_slosh_model.jpg"))
  
  table <- Church_values %>% 
    select(Label, City, value) %>% 
    rename(Parish=Label, Feet=value) %>% 
    sf::st_drop_geometry() %>% 
    arrange(-Feet) %>% 
    gt() %>% 
    tab_header(
      title = md(paste("**Churches affected by Storm Surge from a Cat ",i, "Hurricane**")),
      subtitle="Worst case NOAA SLOSH model, feet above ground level"
    ) %>% 
    tab_source_note(
      source_note="Source: https://www.nhc.noaa.gov/nationalsurge/") %>% 
    fmt_number(
      columns = 3,
      decimals = 1
    ) %>% 
    tab_options(
      column_labels.font.weight = 'bold'
    )
    
  gtsave(table, paste0(output_path, "Cat_",i,"_slosh_model_table.png"))
}

```
