---
title: "St Swithuns"
author: "Alan Jackson"
format: html
editor: source
---

## Create the risk tables for the final document

```{r setup}

library(tidyverse)
library(gt)

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"
out_path <- "/home/ajackson/Dropbox/projects/CeationCareTaskforce/Maps_and_tables/Risk/"

google_CRS <- "EPSG:4326"


Churches <- read_rds(paste0(path, "Parishes.rds")) %>% 
  sf::st_drop_geometry()

```

##    Create dataframe of risks

Name
----
Likelihood          Severity
Low, medium, high   minor, serious, extensive, catastrophic
Coastal flooding
Drought
Hurricanes - cat 1
Hurricanes - cat 2
Hurricanes - cat 3
Ice storms
River flooding
tornado
wildfire
smoke
Hail

```{r}

#   Create a mostly empty dataframe and export as an excel file

# Risks <- Churches %>% 
#   mutate(Parish=paste0(Label, ", ", City)) %>% 
#   select(Parish) %>% 
#   mutate(Coast_Flood_Like="Unk", Coast_Flood_Severe="Unk",
#          Drought_Like="Unk", Drought_Severe="Unk",
#          Hail_Like="Unk", Hail_Severe="Unk",
#          Hurricane1_Like="Unk", Hurricane1_Severe="Unk",
#          Hurricane2_Like="Unk", Hurricane2_Severe="Unk",
#          Hurricane3_Like="Unk", Hurricane3_Severe="Unk",
#          IceStorm_Like="Unk", IceStorm_Severe="Unk",
#          Pluvial_Like="Unk", Pluvial_Severe="Unk",
#          Tornado_Like="Unk", Tornado_Severe="Unk",
#          WildFire_Like="Unk", WildFire_Severe="Unk",
#          Smoke_Like="Unk", Smoke_Severe="Unk"
#   )
#          
#          
# writexl::write_xlsx(Risks, paste0(out_path, "Risk_Matrix.xls"))

```

##        Read in the excel sheet and turn into risk tables

```{r}

df <- readxl::read_excel(paste0(out_path, "Risk_Matrix.xls")) %>% 
  # select(-28) %>% 
  select(-Coast_Flood_Like, -Coast_Flood_Severe) %>% 
  mutate(Flood_First_Like=paste0(as.character(Flood_First_Like), "%")) %>% 
  mutate(Flood_First_Max_Like=paste0(as.character(Flood_First_Max_Like), "%")) %>% 
  mutate(Flood_First_Max_Severe=paste0(as.character(Flood_First_Max_Severe), " ft")) %>% 
  mutate(WildFire_FirstSt_Like=paste0(as.character(WildFire_FirstSt_Like), "%")) %>% 
  mutate(WildFire_FirstSt_Severe=if_else(WildFire_FirstSt_Like=="0%", "Minor", "Medium"))

df2 <- df %>% 
  # head(5) %>% 
  pivot_longer(-Parish, 
               names_to=c("Disaster", ".value"),
               names_pattern="(.+)_(Like|Severe)") %>% 
  rename(Likelihood=Like, Severity=Severe) %>% 
  mutate(Disaster=stringr::str_replace(Disaster, "Tornado1", "EF-0/1 Tornado")) %>% 
  mutate(Disaster=stringr::str_replace(Disaster, "Tornado2", "EF-2+ Tornado")) %>% 
  mutate(Severity=stringr::str_replace(Severity, "Minimal", "Minor"))  
              
foo <- df2 %>% head(12)

maketable <- function(df){
  Parish1 <- df$Parish[1]
  df %>%
    # df2 %>%
      filter(!Likelihood=="None") %>% 
    select(-Parish) %>% 
    mutate(Low="", Medium="", High="",
           Minor="", Major="", Extensive="", Catastrophic="") %>% 
    mutate(
           Low=ifelse(Likelihood=="Low", "X", ""),
           Medium=ifelse(Likelihood=="Medium", "X", ""),
           High=ifelse(Likelihood=="High", "X", ""),
           Minor=ifelse(Severity=="Minor", "X", ""),
           Major=ifelse(Severity=="Major", "X", ""),
           Extensive=ifelse(Severity=="Extensive", "X", ""),
           Catastrophic=ifelse(Severity=="Catastrophic", "X", "")
           ) %>% 
      relocate(Worsen, .after=Catastrophic) %>% 
      select(-Likelihood, -Severity) %>% 
      gt(rowname_col = "Disaster") %>% 
        tab_header(title=paste(Parish1, "Risk Matrix")) %>% 
        tab_spanner(
          label=md("**Likelihood**"),
          columns=c(Low, Medium, High)
        ) %>% 
        tab_spanner(
          label=md("**Severity**"),
          columns=c(Minor, Major, Extensive, Catastrophic)
        ) %>%   
        cols_label(
           "Worsen" = md("**Worsen?**")
        ) %>%
        tab_style(
          style=list(
            cell_borders(
              sides = "all", 
              color = "black", 
              style = "solid"),
            cell_fill(
              color="yellow"
            ) ,
            cell_text(
              weight="bold",
              align="center"
            )
          ),
          locations=cells_body(
            columns=c(2,3,4),
            rows=everything()
          )
         ) %>% 
         tab_style(
          style=list(
            cell_borders(
              sides = "all", 
              color = "black", 
              style = "solid"),
            cell_fill(
              color="pink"
            ), 
            cell_text(
              weight="bold",
              align="center"
            )
          ),
          locations=cells_body(
            columns=c(5,6,7,8),
            rows=everything()
          )
        ) %>%        
        tab_style(
          style=list(
            cell_borders(
              sides = "all", 
              color = "black", 
              style = "solid"),
            cell_fill(
              color="lightskyblue"
            ) ,
            cell_text(
              # weight="bold",
              align="center"
            )
          ),
          locations=cells_body(
            columns=c(9),
            rows=everything()
          )
         )  %>% 
    tab_style(
      style = cell_fill(color = 'red'),
      locations = cells_body(
      columns = c(High), 
      rows = High=="X" 
    ))
      # data_color(
      #   columns = High,
      #   rows = matches("X"),
      #   # method = "numeric",
      #   palette = c("red", "yellow")
      #   # domain = c(0, 50)
      # )
}

Worsen <- tribble(~Worsen,
                  'Yes', 'Unk', "Yes", "Yes", "Yes", "Yes", "Unk", "Yes",
                  "No", "No", "Yes", "Unk")

for (i in 1:163){
  df2 <- df[i,] %>% 
  # head(5) %>% 
  pivot_longer(-Parish, 
               names_to=c("Disaster", ".value"),
               names_pattern="(.+)_(Like|Severe)") %>% 
  rename(Likelihood=Like, Severity=Severe) %>% 
  mutate(Disaster=stringr::str_replace(Disaster, "Hurricane_Surge1", "Cat 1 Surge")) %>% 
  mutate(Disaster=stringr::str_replace(Disaster, "Hurricane_Surge2", "Cat 2 Surge")) %>% 
  mutate(Disaster=stringr::str_replace(Disaster, "Hurricane_Surge3", "Cat 3 Surge")) %>% 
  mutate(Disaster=stringr::str_replace(Disaster, "Hurricane_Surge4", "Cat 4 Surge")) %>% 
  mutate(Disaster=stringr::str_replace(Disaster, "Tornado1", "EF-0/1 Tornado")) %>% 
  mutate(Disaster=stringr::str_replace(Disaster, "Tornado2", "EF-2+ Tornado")) %>% 
  # mutate(Disaster=stringr::str_replace(Disaster, "Coast_Flood", "Coastal Flooding")) %>% 
  mutate(Disaster=stringr::str_replace(Disaster, "IceStorm", "Ice Storm")) %>% 
  mutate(Severity=stringr::str_replace(Severity, "Minimal", "Minor")) %>% 
  mutate(Disaster=stringr::str_replace(Disaster, "Pluvial", "River Flooding"))
  
  df2 <- cbind(df2, Worsen)
  
  table <- maketable(df2)
  gtsave(table, paste0(out_path, 
                       stringr::str_replace_all(df[i,]$Parish, "[ \',\\.]", "_"),
                       "_risk_table.png")) 
  
  if (df[i,]$Parish=="St. David's, Austin"){# St David's Austin
    print(table)
    }
  if (df[i,]$Parish=="St. Luke's on the Lake, Austin"){# St Luke's on the Lake
    print(table)
    }
  if (df[i,]$Parish=="Christ Church Cathedral, Houston"){# Cathedral
    print(table)
    }
  if (df[i,]$Parish=="Trinity, Fort Worth"){# Fort Worth
    print(table)
    }
  if (df[i,]$Parish=="Holy Trinity, Dickinson"){# Dickinson
    print(table)
    }
}


```


## reprex

```{r}

foobar <- tribble(~Col1, ~Col2, ~Col3,
                  "A",    "B",   "C",
                  "Blank row",  "",   "",
                  "D",    "E",   "F",
                  )

foobar %>% 
  gt() %>% 
    cols_merge(
      columns=c(2,3),
      rows=2
    ) 

```


