---
title: "Update_parishes"
author: "Alan Jackson"
format: html
editor: source
---

##    Update parishes - Nov 2025

```{r}
library(tidyverse)
library(sf)

path <- "/home/ajackson/Dropbox/Rprojects/TexasDioceseCreationCare/Data/"

google_crs <- "EPSG:4326" # lat long

Parishes <- readRDS(paste0(path, "Parishes.rds"))

```


```{r}
Parishes[Parishes$ID==152,]$Label <- "All Saints'" 

#################################
# Autry House Houston
#################################
sfc = sf::st_sfc(sf::st_point(c(-95.39642748798482, 29.716510149082165)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

Parishes <- Parishes %>% 
  add_row(ID = 166,
          Label = "Autry House",
          City = "Houston",
          Name = "Autry House: The Episcopal Mission to Rice University",
          Description = "6221 Main Street, Houston, TX 77030",
          Convocation = "East Harris",
          County = "Harris",
          geometry = sfc,
          Zip = "77030",
          Address = "6221 Main Street, Houston, TX 77030")

#################################
# Holy Family Houston
#################################
sfc = sf::st_sfc(sf::st_point(c(-95.33242920741966, 29.754683321408944)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

Parishes <- Parishes %>% 
  add_row(ID = 167,
          Label = "Holy Family",
          City = "Houston",
          Name = "Holy Family Episcopal Church",
          Description = "3719 Navigation Boulevard, Houston, Texas 77003",
          Convocation = "East Harris",
          County = "Harris",
          geometry = sfc,
          Zip = "77003",
          Address = "3719 Navigation Boulevard, Houston, Texas 77003")

#################################
# St Cornelius, Belton
#################################
sfc = sf::st_sfc(sf::st_point(c(-97.46023192897152, 31.14594437684704)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

Parishes <- Parishes %>% 
  add_row(ID = 168,
          Label = "St Cornelius",
          City = "Belton",
          Name = "St Cornelius, Belton",
          Description = "1626 Morgan's Point Rd, Belton, TX 76513",
          Convocation = "Northwest",
          County = "Bell",
          geometry = sfc,
          Zip = "76513",
          Address = "1626 Morgan's Point Rd, Belton, TX 76513")

#################################
# St Brigid Fort Worth
#################################
sfc = sf::st_sfc(sf::st_point(c(-97.32562541281813, 32.74210974084278)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

Parishes <- Parishes %>% 
  add_row(ID = 169,
          Label = "St Brigid",
          City = "Fort Worth",
          Name = "St Brigid, Fort Worth",
          Description = "209 South Main Street, Fort Worth, TX 76104",
          Convocation = "Fort Worth",
          County = "Tarrant",
          geometry = sfc,
          Zip = "76104",
          Address = "209 South Main Street, Fort Worth, TX 76104")

#################################
# St Claires Tyler
#################################
sfc = sf::st_sfc(sf::st_point(c(-95.27222692807565, 32.31261915005325)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

Parishes <- Parishes %>% 
  add_row(ID = 170,
          Label = "St Claires",
          City = "Tyler",
          Name = "St Claires, Tyler",
          Description = "3320 Troup Hwy #260, Tyler, TX 75701",
          Convocation = "Northeast",
          County = "Smith",
          geometry = sfc,
          Zip = "75701",
          Address = "3320 Troup Hwy #260, Tyler, TX 75701")

#################################
# St Esteban Cleveland
#################################
sfc = sf::st_sfc(sf::st_point(c(-95.08120703942448, 30.165700942867193)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

Parishes <- Parishes %>% 
  add_row(ID = 171,
          Label = "St Esteban",
          City = "Cleveland",
          Name = "St Esteban, Cleveland",
          Description = "1680 County Road 3549, Cleveland, TX 77357",
          Convocation = "San Jacinto",
          County = "Liberty",
          geometry = sfc,
          Zip = "77357",
          Address = "1680 County Road 3549, Cleveland, TX 77357")

#################################
# Texas Canterbury Austin
#################################
sfc = sf::st_sfc(sf::st_point(c(-97.73914040796262, 30.291612136848386)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

Parishes <- Parishes %>% 
  add_row(ID = 172,
          Label = "Texas Canterbury",
          City = "Austin",
          Name = "Texas Canterbury, Austin",
          Description = "209 W 27th St, Austin, TX 78705",
          Convocation = "Austin",
          County = "Travis",
          geometry = sfc,
          Zip = "78705",
          Address = "209 W 27th St, Austin, TX 78705")

#################################
# St Peters Lago Vista - closed?
#################################
sfc = sf::st_sfc(sf::st_point(c(-98.01472225397532, 30.434610970675774)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

Parishes <- Parishes %>% 
  add_row(ID = 173,
          Label = "St Peter's",
          City = "Lago Vista",
          Name = "St Peter's, Lago Vista",
          Description = "3305 Pinnacle Cove, Lago Vista, TX 78645",
          Convocation = "Austin",
          County = "Travis",
          geometry = sfc,
          Zip = "78645",
          Address = "3305 Pinnacle Cove, Lago Vista, TX 78645")


saveRDS(Parishes, paste0(path, "Parishes.rds"))

```


##    Minor repairs

```{r}

Parishes <- readRDS(paste0(path, "Parishes.rds"))  

Parishes[Parishes$ID==169,]$Convocation <- "Fort Worth" 

saveRDS(Parishes, paste0(path, "Parishes.rds"))

```

##    Make a truly clean dataset

```{r}

#     Tidy up labels

Parishes[Parishes$ID==109,]$Label <- "St Julian of Norwich" 
Parishes[Parishes$ID==116,]$Label <- "St Peter's" 
Parishes[Parishes$ID==12,]$Label <- "St Peter's and San Pedro" 
Parishes[Parishes$ID==142,]$Label <- "St Michael & All Angels" 
Parishes[Parishes$ID==144,]$Label <- "St Paul's" 
Parishes[Parishes$ID==126,]$Label <- "St Joseph's" 
Parishes[Parishes$ID==45,]$Label <- "All Saints'" 
Parishes[Parishes$ID==20,]$Label <- "Holy Apostles'" 
Parishes[Parishes$ID==27,]$Label <- "St Francis'" 
Parishes[Parishes$ID==165,]$Label <- "St Isidore's" 
Parishes[Parishes$ID==168,]$Label <- "St Cornelius'" 
Parishes[Parishes$ID==169,]$Label <- "St Brigid's" 
Parishes[Parishes$ID==170,]$Label <- "St Claire's" 
Parishes[Parishes$ID==171,]$Label <- "St Esteban's" 
Parishes[Parishes$ID==16,]$Label <- "Ascension" 
Parishes[Parishes$ID==151,]$Label <- "Resurrection" 
Parishes[Parishes$ID==162,]$Label <- "Faith" 
Parishes[Parishes$ID==102,]$Label <- "St Christopher's" 

Parishes <- Parishes %>% 
  select(ID, Label, City, Convocation, County, Zip, Address, Description)

Parishes <- Parishes %>% 
  sf::st_as_sf()

saveRDS(Parishes, paste0(path, "Clean_Parishes.rds"))


```

##    Add churches to clean version

```{r}

Parishes <- readRDS(paste0(path, "Clean_Parishes.rds")) 
  
Parishes[Parishes$ID==66,]$Label <- "St Christopher's" 
Parishes[Parishes$ID==117,]$Label <- "St Richard's" 
Parishes[Parishes$ID==39,]$Label <- "St Dunstan's" 
Parishes[Parishes$ID==154,]$Label <- "St Luke's in the Meadow" 

Parishes <- Parishes %>% 
  mutate(Status="Open")

Parishes[Parishes$ID==116,]$Status <- "Closed" 

  
#################################
# St Peters Lago Vista - closed?
#################################
sfc = sf::st_sfc(sf::st_point(c(-98.01472225397532, 30.434610970675774)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

Parishes <- Parishes %>% 
  add_row(ID = 173,
          Label = "St Peter's",
          City = "Lago Vista",
          Convocation = "Austin",
          County = "Travis",
          Zip = "78645",
          Address = "3305 Pinnacle Cove, Lago Vista, TX 78645",
          Description = "3305 Pinnacle Cove, Lago Vista, TX 78645",
          geometry = sfc)

saveRDS(Parishes, paste0(path, "Clean_Parishes.rds"))

```

##    Add St Stephen's school 26 Apr 2026

```{r}
Parishes <- readRDS(paste0(path, "Clean_Parishes.rds")) 

Parishes <- Parishes %>% 
  mutate(Zip=as.character(Zip))
  
#################################
# St Stephen's school
#################################
sfc = sf::st_sfc(sf::st_point(c(-97.81917743079927, 30.330547540331125)))
sf::st_geometry(sfc)
sf::st_crs(sfc) <- google_crs

Parishes <- Parishes %>% 
  add_row(ID = 175,
          Label = "St Stephen's",
          City = "Austin",
          Convocation = "Austin",
          County = "Travis",
          Zip = "78746",
          Address = "6500 St Stephens Dr, Austin, TX 78746",
          Description = "6500 St Stephens Dr, Austin, TX 78746",
          Status = "Open",
          geometry = sfc)

Parishes[Parishes$ID==175,]$Status <- "Open" 
Parishes[Parishes$ID==175,]$Label <- "St Stephen's School" 
Parishes[Parishes$ID==33,]$City <- "Atascosita" 

saveRDS(Parishes, paste0(path, "Clean_Parishes.rds"))

```


##    Add ID to spreadsheet

```{r}

Parishes <- readRDS(paste0(path, "Clean_Parishes.rds")) %>% 
  sf::st_drop_geometry() %>% 
  mutate(across(everything(), stringr::str_trim)) %>% 
  mutate(Label=stringr::str_remove(Label, "\'"))

df <- readxl::read_excel(paste0(path, "Survey_contacts.xlsx")) %>% 
  filter(!is.na(City)) %>%
  select(-1) %>% 
  mutate(across(everything(), stringr::str_trim)) %>% 
  mutate(Congregation=stringr::str_remove(Congregation, "\'"))

foo <- full_join(Parishes, df, by=c("Label" = "Congregation", "City"))

```

##    Save as excel file

```{r}

foo %>% 
  rename(Congregation=Label, Label=Label.y) %>% 
  filter(!Status=="Closed") %>% 
  writexl::write_xlsx(path=paste0(path, "Survey_contacts_2.xlsx"))


```





